version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: netflix_postgres
    restart: always
    environment:
      POSTGRES_USER: netflixuser
      POSTGRES_PASSWORD: netflixpass
      POSTGRES_DB: netflixdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: